// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/thebartekbanach/imcaxy/pkg/proxy (interfaces: ProxyResponseWriter)

// Package mock_proxy is a generated GoMock package.
package mock_proxy

import (
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProxyResponseWriter is a mock of ProxyResponseWriter interface.
type MockProxyResponseWriter struct {
	ctrl     *gomock.Controller
	recorder *MockProxyResponseWriterMockRecorder
}

// MockProxyResponseWriterMockRecorder is the mock recorder for MockProxyResponseWriter.
type MockProxyResponseWriterMockRecorder struct {
	mock *MockProxyResponseWriter
}

// NewMockProxyResponseWriter creates a new mock instance.
func NewMockProxyResponseWriter(ctrl *gomock.Controller) *MockProxyResponseWriter {
	mock := &MockProxyResponseWriter{ctrl: ctrl}
	mock.recorder = &MockProxyResponseWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProxyResponseWriter) EXPECT() *MockProxyResponseWriterMockRecorder {
	return m.recorder
}

// WriteError mocks base method.
func (m *MockProxyResponseWriter) WriteError(arg0 int, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WriteError", arg0, arg1)
}

// WriteError indicates an expected call of WriteError.
func (mr *MockProxyResponseWriterMockRecorder) WriteError(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteError", reflect.TypeOf((*MockProxyResponseWriter)(nil).WriteError), arg0, arg1)
}

// WriteErrorWithFallback mocks base method.
func (m *MockProxyResponseWriter) WriteErrorWithFallback(arg0 int, arg1 string, arg2 io.ReadCloser) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WriteErrorWithFallback", arg0, arg1, arg2)
}

// WriteErrorWithFallback indicates an expected call of WriteErrorWithFallback.
func (mr *MockProxyResponseWriterMockRecorder) WriteErrorWithFallback(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteErrorWithFallback", reflect.TypeOf((*MockProxyResponseWriter)(nil).WriteErrorWithFallback), arg0, arg1, arg2)
}

// WriteOK mocks base method.
func (m *MockProxyResponseWriter) WriteOK(arg0 io.ReadCloser) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WriteOK", arg0)
}

// WriteOK indicates an expected call of WriteOK.
func (mr *MockProxyResponseWriterMockRecorder) WriteOK(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteOK", reflect.TypeOf((*MockProxyResponseWriter)(nil).WriteOK), arg0)
}
