name: Release


on:
  release:
    types: [published, unpublished, deleted]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Prepare test env
      run:  cp ./config/env/examples/* ./config/env && cd config/env && sed -i 's/Dev/IntegrationTests/' Imcaxy.Server.env && for filename in *.env; do mv "$filename" "IntegrationTests.$filename"; done;

    - name: Test 
      run: docker compose -f integration-tests.docker-compose.yml up integration-tests-imcaxy-imaginary integration-tests-imcaxy-mongo integration-tests-imcaxy-minio --detach --remove-orphans && docker compose -f integration-tests.docker-compose.yml up integration-tests-imcaxy-server --no-log-prefix
      
    - name: Cleanup test env
      run: docker-compose -f integration-tests.docker-compose.yml down --volumes --remove-orphans && rm ./config/env/*.env
      
    - name: Prepare build env
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v -o ./bin/server ./cmd/server
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./bin/server
    
